Dhofar360/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('index/', include('main.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('pho/', include('pho.urls')),
    path('place/', include('place.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pho/urls.py
from django.urls import path, include
from .views import index, add_new_p, delete, editp, edit_p, search
app_name="pho"
urlpatterns = [
    path('', index),
    path('index/', index),
    path('add_new_p/', add_new_p),
    path('delete/<int:id>/',delete, name="delete"),
    path('editp/<int:id>/',editp, name="editp"),
    path('edit_p/', edit_p),
    path('search/', search),

]

place/urls.py
from django.urls import path, include
from .views import index, add_new_pl, delete, editpl, edit_pl, search,uploadimg,addcomment
app_name="place"
urlpatterns = [
    path('', index),
    path('index/', index),
    path('uploadimg/', uploadimg),
    path('add_new_pl/', add_new_pl),
    path('delete/<int:id>/',delete, name="delete"),
    path('editpl/<int:id>/',editpl, name="editpl"),
    path('edit_pl/', edit_pl),
    path('search/', search),
    path('addcomment/', addcomment, name="addcomment"),




]

place/models.py
from django.db import models
from pho.models import Photographer

# Create your models here.
class Place(models.Model):
    plname=models.CharField(verbose_name="Title Name", max_length=100,null=True, blank=True)
    plstext=models.CharField(verbose_name="Stext", max_length=100,null=True, blank=True)
    plstate=models.CharField(verbose_name="State", max_length=100,null=True, blank=True)
    pllat=models.CharField(verbose_name="Lat", max_length=100,null=True, blank=True)
    pllang=models.CharField(verbose_name="Lang", max_length=100,null=True, blank=True)
    pldesc=models.TextField(verbose_name="Description",null=True, blank=True)


    def __str__(self):
        return self.plname

class Image(models.Model):
    imgname=models.CharField(verbose_name="Image Name", max_length=200,null=True, blank=True)
    pname=models.ForeignKey(Photographer, on_delete=models.CASCADE, related_name="pho_data")
    #uploadImg=models.ImageField(upload_to = 'pic_folder/%Y/%m/%d/%H/%M/%S/', default = 'pic_folder/None/no-img.jpg')
    uploadImg=models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')
    plname=models.ForeignKey(Place, on_delete=models.CASCADE, related_name="place_data")
    desc=models.TextField(max_length=100,null=True, blank=True)
    status=models.BooleanField(default=False)
    main_img=models.BooleanField(default=False)

    def __str__(self):
        return self.imgname


class GustComment(models.Model):
    comtitle=models.CharField(verbose_name="Comment Title",max_length=200, null=True, blank=True)
    comments=models.TextField(verbose_name="Comments",null=True, blank=True)
    status=models.BooleanField(default=False)
    plname=models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        return self.comtitle

class Comment(models.Model):
    ctitle=models.CharField(verbose_name="Title", max_length=200,null=True, blank=True)
    cdetail=models.TextField(verbose_name="Detail",null=True, blank=True)
    plname=models.ForeignKey(Place, on_delete=models.CASCADE)
    pname=models.ForeignKey(Photographer, on_delete=models.CASCADE, default=3)

    def __str__(self):
        return self.ctitle

place/forms.py
from django import forms
from .models import Place, Image

class PlaceForm(forms.ModelForm):
    class Meta:
        model=Place
        #fields = '__all__'
        fields=['plname','plstext','plstate','pllat','pllang','pldesc']


class ImgForm(forms.ModelForm):
    class Meta:
        model=Image
        fields=['imgname','pname','plname','uploadImg','status', 'desc','main_img']

place/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from .models import Place,GustComment
from .forms import PlaceForm, ImgForm

def index(request):
    pl_data=Place.objects.all()
    context={
        'pllst':pl_data,
        }
    return render(request,"place/place.html",context)

#add new comments------------------------------------------------------------------------
def addcomment(request):
    getpostid=""
    if request.method=="POST":
        getCom=GustComment(); #create instance of the model GustComment
        getCom.comtitle=request.POST.get("comtitle")
        getCom.comments=request.POST.get("comment")
        getCom.plname=Place.objects.get(id=int(request.POST.get("did")))
        getCom.save()
        getpostid=request.POST.get("did") #this is to get the post id

    #get all the comments about the same post
   #getcomments=GustComment.objects.all().filter(plname=getpostid)


    return redirect('main:detail',id=getpostid) #render(request,"index.html")
    #return redirect('main:detail', kwargs={'id':getpostid})
    #return redirect(reverse('main:detail', kwargs={'id':getpostid,'allcom':getcomments}))

#----------------------------------------------------------------------------------------
def search(request):
    #checking to see if the request method is post or get
    if request.method =="POST":
        #search the database for the places with the name stored inside the argument "plname" which comes with post
        plt=request.POST.get('pltitle')
        #getstn= places.objects.all()[:1].get() #getting the first record
        getplt=Place.objects.get(pltitle=plt)

    #return HttpResponse("<h1>" + getstn.stname + "</h1>")
    return render(request,"place/search.html",{'result':getplt})

#edit place here it will open the edit_st.html to display the data which will be modified
def editpl(request, id):
    getpl=Place.objects.get(id=id)

    return render(request,"place/edit_pl.html",{'result':getpl})
    #return HttpResponse("<h1>" + getst.stname + "</h1>")

#upload images
def uploadimg(request):
    form = ImgForm()
    return render(request,"uploadimg.html", {'form' : form})

#this will send the modified data to the be saved in the databae
def edit_pl(request):
    msg=""
    if request.method=="POST":
        pl=request.POST.get('id') #getting the id of the Place which will be saved. the id will be sent inside a hidden filed from the form
        getplaces=Place.objects.get(id=pl)
        getplaces.pltitle=request.POST.get('pltitle')
        getplaces.plid=request.POST.get('plid')
        getplaces.plstext=request.POST.get('plstext')
        getplaces.plstate=request.POST.get('plstate')
        getplaces.pllat=request.POST.get('pllat')
        getplaces.pllang=request.POST.get('pllang')

        getplaces.save()

        msg="places data updates successfully"
    else:
        msg="places data not update please see the administrator"

    pl_data=Place.objects.all()
    context={
        'pllst':pl_data,
        'msg':msg
        }
    return render(request,"place/place.html",context)

def delete(request, id):
    # id is the place id, we we get it from the form index.html
    # here we must check to see if the place with the id is there in the database or not
    obj=get_object_or_404(places,id=id)
    if obj:
        obj.delete()
        msg="places Deleted!"
    else:
        msg="places Not Deleted"

    pl_data=Place.objects.all()
    context={
        'pllst':pl_data,
        'msg':msg
        }
    return render(request,"place/place.html",context)

#Add New place ----------------------------------------------------------------
def add_new_pl(request):
    #getting the list of all places
    #pl_data=places.objects.all()
    #form = PlaceForm(request.POST or None)
    form=PlaceForm()
    #check to see if the request method is post or not
    if request.method=="POST":
        # Getting the posted data (the Place name and Place title )
        plt=request.POST.get("pltitle")
        pname=request.POST.get("pname")
        pls=request.POST.get("plstext")
        plst=request.POST.get("plstate")
        pll=request.POST.get("pllat")
        plla=request.POST.get("pllang")

        # adding data to the model
        place=Place(pltitle=plt, pname_id=pname, plstext=pls, plstate=plst, pllat=pll, pllang=plla  )
        place.save()
        context= {'form': form}
        return render(request, "place/place.html", context)
    else:
        #Here we are importing a form

        context= {'form': form}
        return render(request, "place/place.html", context)


#def delete(request, id):
  #  pass

templates/place/edit_pl.html
<h2>Please change the data as required !</h2>
<hr>
<form action="/place/edit_pl/" method="POST">
    {% csrf_token %}
    <input type="hidden"  name="id" value="{{result.id}}">
    places Title:<input type="text" name="pltitle" value="{{result.pltitle}}"><br>
    places ID:<input type="text" name="plid" value="{{result.plid}}"><br>
    places Stext:<input type="text" name="plstext" value="{{result.plstext}}"><br>
    places State:<input type="text" name="plstate" value="{{result.plstate}}"><br>
    places Lat:<input type="text" name="pllat" value="{{result.pllat}}"><br>
    places Lang:<input type="text" name="pllang" value="{{result.pllang}}"><br>
    <input type="submit" name="save changes">



</form>

templates/place/place.html
<!-- <form action="/place/search/" method="POST">
    {% csrf_token %}
    <input type="text" name="pltitle"> <br>
    <input type="submit" name="Find">
</form> -->

<form action="/place/add_new_pl/"  method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit"  name="Add New places">
</form>
<hr>
<br>
<style>
    td{
        border:1px solid #000;
    }
    td.hd{
        background-color:#c1c1c1;
    }
</style>
<table class="table">
    <tr>
        <td class="hd">Title</td>
        <td class="hd">ID</td>
        <td class="hd">Stext</td>
        <td class="hd">State</td>
        <td class="hd">Lat</td>
        <td class="hd">Lang</td>
        <td></td>
    </tr>
    {% for  pl in pllst  %}
    <tr>
        <td>{{pl.pltitle}}</td>
        <td>{{pl.plid}}</td>
        <td>{{pl.plstext}}</td>
        <td>{{pl.plstate}}</td>
        <td>{{pl.pllat}}</td>
        <td>{{pl.pllang}}</td>
        <td><a href="{% url 'place:editpl' id=pl.id %}">Edit</a></td>
        <td><a onclick="return confirm('Are you sure you want to delete this place?');" href="{% url 'place:delete' id=pl.id %}">Delete</a></td>

    </tr>
    {% endfor %}
</table>

templates/place/search.html
<h1>The Result is:</h1>
places Title:{{result.pltitle}} <br>
places ID:{{result.plid}}<br>
places Stext:{{result.plstext}} <br>
places State:{{result.plstate}} <br>
places Lat:{{result.pllat}} <br>
places Lang:{{result.pllang}}