Dhofar360/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('index/', include('main.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('pho/', include('pho.urls')),
    path('place/', include('place.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pho/urls.py
from django.urls import path, include
from .views import index, add_new_p, delete, editp, edit_p, search
app_name="pho"
urlpatterns = [
    path('', index),
    path('index/', index),
    path('add_new_p/', add_new_p),
    path('delete/<int:id>/',delete, name="delete"),
    path('editp/<int:id>/',editp, name="editp"),
    path('edit_p/', edit_p),
    path('search/', search),

]

pho/models.py
from django.db import models

# Create your models here.
class Photographer(models.Model):
    pname=models.CharField(verbose_name="photographer Name", max_length=100,null=True, blank=True)
    address=models.CharField(verbose_name="Address", max_length=100,null=True, blank=True)
    email=models.CharField(verbose_name="Email", max_length=100,null=True, blank=True)
    mobile=models.CharField(verbose_name="Mobile", max_length=100,null=True, blank=True)
    facebook=models.CharField(verbose_name="Facebook", max_length=100,null=True, blank=True)
    twitter=models.CharField(verbose_name="Twitter", max_length=100,null=True, blank=True)
    instagram=models.CharField(verbose_name="Instagram", max_length=100,null=True, blank=True)
    desc=models.TextField(verbose_name="Description", null=True, blank=True)
    uploadImg=models.ImageField(upload_to = 'pic_pho/', default = 'pic_pho/None/no-img.jpg')


    def __str__(self):
        return self.pname


class Uploadimg(models.Model):
    imgtitle=models.CharField(verbose_name="Title", max_length=200, null=True, blank=True)
    uploaded_at=models.DateTimeField(auto_now_add=True)
    pname=models.ForeignKey(Photographer, on_delete=models.CASCADE)
    imgupload=models.ImageField(upload_to ='pic_folder')

    def __str__(self):
        return self.imgtitle

pho/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Photographer

#the first welcome page
def index(request):
    p_data=Photographer.objects.all().order_by("pname")[:3]

    return render(request, "index.html", {'plst':p_data})
    #return redirect('/photo/cjsonfile/')
    #return render(request, "photo/index.html")

# search the website
def search(request):
    #checking to see if the request method is post or get
    if request.method =="POST":
        #search the database for the photographer with the name stored inside the argument "stname" which comes with post
        pn=request.POST.get('pname')
        #getstn= photographer.objects.all()[:1].get() #getting the first record
        getpn=Photographer.objects.get(pname=pn)

    #return HttpResponse("<h1>" + getstn.stname + "</h1>")
    return render(request,"pho/search.html",{'result':getpn})


#edit photographer here it will open the edit_st.html to display the data which will be modified
def editp(request, id):
    getp=Photographer.objects.get(id=id)

    return render(request,"pho/edit_p.html",{'result':getp})
    #return HttpResponse("<h1>" + getst.stname + "</h1>")


#this will send the modified data to the be saved in the databae
def edit_p(request):
    msg=""
    if request.method=="POST":
        p=request.POST.get('id') #getting the id of the student which will be saved. the id will be sent inside a hidden filed from the form
        getphotographer=Photographer.objects.get(id=p)
        getphotographer.pname=request.POST.get('pname')
        getphotographer.pid=request.POST.get('pid')
        getphotographer.pimage=request.POST.get('pimage')
        getphotographer.pstate=request.POST.get('pstate')
        getphotographer.porder=request.POST.get('porder')
        getphotographer.pstext=request.POST.get('pstext')

        getphotographer.save()

        msg="photographer data updates successfully"
    else:
        msg="photographer data not update please see the administrator"

    p_data=Photographer.objects.all()
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)


def delete(request, id):
    # id is the photographer id, we we get it from the form index.html
    # here we must check to see if the photographer with the id is there in the database or not
    obj=get_object_or_404(Photographer,id=id)
    if obj:
        obj.delete()
        msg="photographer Deleted!"
    else:
        msg="photographer Not Deleted"

    p_data=Photographer.objects.all()
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)

#Add New photographer
def add_new_p(request):
    #Here we are going to declare a variable to hold the message
    msg=""
    #check to see if the request method is post or not
    if request.method=="POST":
        # Getting the posted data (the student name and student collage)
        pn=request.POST.get("pname")
        pi=request.POST.get("pid")
        pim=request.POST.get("pimage")
        ps=request.POST.get("pstate")
        po=request.POST.get("porder")
        pst=request.POST.get("pstext")


        # adding data to the model
        pho=Photographer(pname=pn, pid=pi, pimage=pim, pstate=ps, porder=po, pstext=pst  )
        pho.save()
        msg="photographer data was saved"
    else:
        msg="photographer Data Not Saved!!"

    #here we are retrieving all the data from the student's table
    p_data=Photographer.objects.all()

    #here we are creating a dictionary to hold the retrived data and also the message
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)

templates/pho/edit_p.html
<h2>Please change the data as required !</h2>
<hr>
<form action="/pho/edit_p/" method="POST">
    {% csrf_token %}
    <input type="hidden"  name="id" value="{{result.id}}">
    photographer Name:<input type="text" name="pname" value="{{result.pname}}"><br>
    photographer ID:<input type="text" name="pid" value="{{result.pid}}"><br>
    photographer pImg:<input type="text" name="pimage" value="{{result.pimage}}"><br>
    photographer stext:<input type="text" name="pstext" value="{{result.pstext}}"><br>
    photographer state:<input type="text" name="pstate" value="{{result.pstate}}"><br>
    photographer order:<input type="text" name="porder" value="{{result.porder}}"><br>
    <input type="submit" name="save changes">



</form>

templates/pho/pho.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<form action="/pho/search/" method="POST">
    {% csrf_token %}
    <input type="text" name="pname"> <br>
    <input type="submit" name="Find">
</form>

<form action="/pho/add_new_p/"  method="POST">
    {% csrf_token %}
    photographer Name:<input type="text" name="pname"><br>
    photographer ID:<input type="text" name="pid"><br>
    photographer pImg:<input type="text" name="pimage"><br>
    photographer stext:<input type="text" name="pstext"><br>
    photographer state:<input type="text" name="pstate"><br>
    photographer order:<input type="text" name="porder"><br>




    <input type="submit"  name="Add New photographer">
</form>
<hr>
{{msg}}
<!-- Load image manually -->
<img src="{% static "ph/download.jpg" %}" style="max-width:200px;">
<table class="table">
     <tr>
        <td><img src="{% static "ph/download.jpg" %}" style="max-width:50px;"></td>
        <td><img src="{% static "ph/download.jpg" %}" style="max-width:50px;"></td>
        <td><img src="{% static "ph/download.jpg" %}" style="max-width:50px;"></td>
        <td><img src="{% static "ph/download.jpg" %}" style="max-width:50px;"></td>
        <td><img src="{% static "ph/download.jpg" %}" style="max-width:50px;"></td>
 </tr>
</table>
<br>
<style>
    td{
        border:1px solid #000;
    }
    td.hd{
        background-color:#c1c1c1;
    }
</style>
<table class="table">
    <tr>
        <td class="hd">Name</td>
        <td class="hd">ID</td>
        <td class="hd">pImg</td>
        <td class="hd">stext</td>
        <td class="hd">state</td>
        <td class="hd">order</td>
        <td></td>
    </tr>
    {% for  p in plst  %}
    <tr>
        <td>{{p.pname}}</td>
        <td>{{p.pid}}</td>
        <td>{{p.pimage}}</td>
        <td>{{p.pstext}}</td>
        <td>{{p.pstate}}</td>
        <td>{{p.porder}}</td>
        <td><a href="{% url 'pho:editp' id=p.id %}">Edit</a></td>
        <td><a onclick="return confirm('Are you sure you want to delete this photographer?');" href="{% url 'pho:delete' id=p.id %}">Delete</a></td>

    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/pho/search.html
<h1>The Result is:</h1>
photographer Name:{{result.pname}} <br>
photographer ID:{{result.pid}}<br>
photographer pImg:{{result.pimage}} <br>
photographer stext:{{result.pstext}} <br>
photographer state:{{result.pstate}} <br>
photographer order:{{result.porder}}