Dhofar360/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('index/', include('main.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('pho/', include('pho.urls')),
    path('place/', include('place.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index,detail,pho_detail
app_name="main"
urlpatterns=[
    path('', index, name="main_page"),
    path('index/', index, name="main_page"),
    path('detail/', detail, name="detail"),
    path('detail/<int:id>', detail, name="detail"),
    path('pho_detail/<int:id>', pho_detail, name="pho_detail"),
    ]

pho/urls.py
from django.urls import path, include
from .views import index, add_new_p, delete, editp, edit_p, search
app_name="pho"
urlpatterns = [
    path('', index),
    path('index/', index),
    path('add_new_p/', add_new_p),
    path('delete/<int:id>/',delete, name="delete"),
    path('editp/<int:id>/',editp, name="editp"),
    path('edit_p/', edit_p),
    path('search/', search),

]

pho/models.py
from django.db import models

# Create your models here.
class Photographer(models.Model):
    pname=models.CharField(verbose_name="photographer Name", max_length=100,null=True, blank=True)
    address=models.CharField(verbose_name="Address", max_length=100,null=True, blank=True)
    email=models.CharField(verbose_name="Email", max_length=100,null=True, blank=True)
    mobile=models.CharField(verbose_name="Mobile", max_length=100,null=True, blank=True)
    facebook=models.CharField(verbose_name="Facebook", max_length=100,null=True, blank=True)
    twitter=models.CharField(verbose_name="Twitter", max_length=100,null=True, blank=True)
    instagram=models.CharField(verbose_name="Instagram", max_length=100,null=True, blank=True)
    desc=models.TextField(verbose_name="Description", null=True, blank=True)
    uploadImg=models.ImageField(upload_to = 'pic_pho/', default = 'pic_pho/None/no-img.jpg')


    def __str__(self):
        return self.pname


class Uploadimg(models.Model):
    imgtitle=models.CharField(verbose_name="Title", max_length=200, null=True, blank=True)
    uploaded_at=models.DateTimeField(auto_now_add=True)
    pname=models.ForeignKey(Photographer, on_delete=models.CASCADE)
    imgupload=models.ImageField(upload_to ='pic_folder')

    def __str__(self):
        return self.imgtitle

pho/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Photographer

#the first welcome page
def index(request):
    p_data=Photographer.objects.all().order_by("pname")[:3]

    return render(request, "index.html", {'plst':p_data})
    #return redirect('/photo/cjsonfile/')
    #return render(request, "photo/index.html")

# search the website
def search(request):
    #checking to see if the request method is post or get
    if request.method =="POST":
        #search the database for the photographer with the name stored inside the argument "stname" which comes with post
        pn=request.POST.get('pname')
        #getstn= photographer.objects.all()[:1].get() #getting the first record
        getpn=Photographer.objects.get(pname=pn)

    #return HttpResponse("<h1>" + getstn.stname + "</h1>")
    return render(request,"pho/search.html",{'result':getpn})


#edit photographer here it will open the edit_st.html to display the data which will be modified
def editp(request, id):
    getp=Photographer.objects.get(id=id)

    return render(request,"pho/edit_p.html",{'result':getp})
    #return HttpResponse("<h1>" + getst.stname + "</h1>")


#this will send the modified data to the be saved in the databae
def edit_p(request):
    msg=""
    if request.method=="POST":
        p=request.POST.get('id') #getting the id of the student which will be saved. the id will be sent inside a hidden filed from the form
        getphotographer=Photographer.objects.get(id=p)
        getphotographer.pname=request.POST.get('pname')
        getphotographer.pid=request.POST.get('pid')
        getphotographer.pimage=request.POST.get('pimage')
        getphotographer.pstate=request.POST.get('pstate')
        getphotographer.porder=request.POST.get('porder')
        getphotographer.pstext=request.POST.get('pstext')

        getphotographer.save()

        msg="photographer data updates successfully"
    else:
        msg="photographer data not update please see the administrator"

    p_data=Photographer.objects.all()
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)


def delete(request, id):
    # id is the photographer id, we we get it from the form index.html
    # here we must check to see if the photographer with the id is there in the database or not
    obj=get_object_or_404(Photographer,id=id)
    if obj:
        obj.delete()
        msg="photographer Deleted!"
    else:
        msg="photographer Not Deleted"

    p_data=Photographer.objects.all()
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)

#Add New photographer
def add_new_p(request):
    #Here we are going to declare a variable to hold the message
    msg=""
    #check to see if the request method is post or not
    if request.method=="POST":
        # Getting the posted data (the student name and student collage)
        pn=request.POST.get("pname")
        pi=request.POST.get("pid")
        pim=request.POST.get("pimage")
        ps=request.POST.get("pstate")
        po=request.POST.get("porder")
        pst=request.POST.get("pstext")


        # adding data to the model
        pho=Photographer(pname=pn, pid=pi, pimage=pim, pstate=ps, porder=po, pstext=pst  )
        pho.save()
        msg="photographer data was saved"
    else:
        msg="photographer Data Not Saved!!"

    #here we are retrieving all the data from the student's table
    p_data=Photographer.objects.all()

    #here we are creating a dictionary to hold the retrived data and also the message
    context={
        'plst':p_data,
        'msg':msg
        }
    return render(request,"pho/pho.html",context)

templates/_footer.html
<footer class="text-muted" style="background-color:#333a40;color:#fff;">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/_header.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Fontawsom for icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- mapbox cdn -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <style>
        .p-img{
            position:relative;
        }
        img.pho{
            position: absolute;
            top: 0;
            right: 0;
            margin-top: 180px;
            margin-right: 10px;
            border: 3px solid #fff;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About Dhofar360</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a  href="{% url 'main:main_page' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <!-- <strong>Dhofar360</strong> -->
        <img src="{% static "/assets/logodh4.png" %}" alt="Dhofar360" style="max-height:40px;">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

templates/details.html
{% include "_header.html" %}
<main role="main">
  <section class="jumbotron text-center" style="background: url(media/{{mimg}}) no-repeat center center;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
    <div class="container" style="background-color:rgba(0,0,0,0.3);">
      <h1 class="jumbotron-heading" style="color:#fff;font-weight:bold;">{{imgname}}</h1>
      <p class="lead text-muted" style="color:#fff !important;">{{desc}}</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>

      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      <!-- here i make a loop to bring all the place data from the database -->

        <div class="col">
            {% for f in getimg %}
            <img src="{{f.uploadImg.url}}" style="height:100%;width:100%;">
            {% endfor %}


        </div>
        <div class="col">
                {% for i in pldetail %}
                    <h2 style="font-weight:bold;color:#333;">{{i.plname}}</h2><br>
                    <hr>
                    <p style="font-weight:normal;font-size:12px;color:#888;">
                      {{i.pldesc}}
                    </p>

                {% endfor %}

       <!-- end of the loop -->
      </div>
    </div>

    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css" rel="stylesheet" />



    <div class="row" style="margin-top:20px;">
        <div class="col">

            <!-- this is the image of the place -->
    <!--             style: 'mapbox://styles/mapbox/streets-v10', -->
             <div id='map' style='width: 100%; height: 300px;'></div>

<script>
 mapboxgl.accessToken = 'pk.eyJ1IjoidGFib29rMjIiLCJhIjoiY2s0djZ0bWFrMGQ1dTNrcjhhdXcyeTZibiJ9.Rc2IFSD2eyjcmYRcqQjtXA';

/* Map: This represents the map on the page. */
var map = new mapboxgl.Map({
container: "map",
style: 'mapbox://styles/mapbox/streets-v10',
 center: [{{lang}}, {{lat}}],
            zoom:10,
            bearing: 180
});

map.on("load", function () {
/* Image: An image is loaded and added to the map. */
map.loadImage("https://i.imgur.com/MK4NUzI.png", function(error, image) {
if (error) throw error;
map.addImage("custom-marker", image);
/* Style layer: A style layer ties together the source and image and specifies how they are displayed on the map. */
map.addLayer({
id: "markers",
type: "symbol",
/* Source: A data source specifies the geographic coordinate where the image marker gets placed. */
source: {
type: "geojson",
data: {
type: 'FeatureCollection',
features: [
{
type: 'Feature',
properties: {},
geometry: {
type: "Point",
coordinates:  [{{lang}}, {{lat}}],
}
}
]
}
},
layout: {
"icon-image": "custom-marker",
}
});
});
});



</script>


        </div>
    </div>
    <div class="row" style="margin-top:100px;margin-bottom:100px;">
        <div class="col">
            <form action="/place/addcomment/" method="POST">
                {% csrf_token %}
                <!-- Hidden file -->
                <input type="hidden" name="did" value="{{id}}">

                <div class="form-group row">
                <label for="inputComTitle" class="col-sm-2 col-form-label">Comment Title</label>
                <div class="col-sm-10">
                <input type="text" class="form-control" name="comtitle" id="comtitle"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <label for="inputComments" class="col-sm-2 col-form-label">Comments</label>
                <div class="col-sm-10">
                <textarea rows="4" cols="50" class="form-control" name="comment" id="comment"></textarea>
                </div>
              </div>
               <button type="submit" class="btn btn-primary mb-2" style="position:absolute; right:0;">Send Comments</button>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col">

        here we are going to add the list of commets, the must be order from the latest

        {% for cm in getc %}
        <h2 style="font-size:16px;color:#4338E8;">
          <i class="far fa-comments" style="margin-right:10px;"></i>{{cm.comtitle}}
        </h2>
        <hr>
        <p style="background-color:#f1f1f1;font-weight:normal;color:#323133;font-size:12px;
            max-width:75%;
            border:1px solid #f1f1f1;margin-left:50px;
            padding:10px;">
            {{cm.comments}}
        </p>
        {% endfor %}
        </div>
    </div>
  </div>

</main>
{% include "_footer.html" %}

templates/index.html
{% include "_header.html" %}
<main role="main">
  <section class="jumbotron text-center" style="background: url(media/{{mimg}}) no-repeat center center;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;">
    <div class="container" style="background-color:rgba(0,0,0,0.3);">
      <h1 class="jumbotron-heading" style="color:#fff;font-weight:bold;">{{imgname}}</h1>
      <p class="lead text-muted" style="color:#fff !important;">{{desc}}</p>
      <p>
      <!--  <a href="#" class="btn btn-primary my-2">Move</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->

      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      <!-- here i make a loop to bring all the student data from the database -->
          {% for i in plst %}
               <div class="col-md-4">
               <div class="card mb-4 shadow-sm">
                   <div class="p-img">
                        <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{i.uploadImg.url}}">
                        <!--<img class="pho" src="media/pho/pho1.png" style=" height:80px;width:80px;border-radius: 50%;">-->
                       <a href="{% url 'main:pho_detail' id=i.pname.id %}"> <img class="pho" src="{{i.pname.uploadImg.url}}" style=" height:80px;width:80px;border-radius: 50%;"></a>
                   </div>

               <div class="card-body">
                  <p class="card-text" style="font-weight:bold;color:#888;">{{i.plname}}</p>
                  <hr>
                  <p style="font-size:12px;">
                       {{i.plname.plstext}}
                  </p>



                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">

                      <a class="btn btn-sm btn-outline-secondary" href="{% url 'main:detail' id=i.plname.id %}">view More</a>
                    </div>
                    <!-- <small class="text-muted">9 mins</small> -->
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          <!-- end of the loop -->
      </div>
    </div>
  </div>

</main>
{% include "_footer.html" %}

templates/pho.html
{% include "_header.html" %}
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      <!-- here i make a loop to bring all the place data from the database -->
       {% for i in phodetail %}
       <div class="col" style="height:200px;">
            <img src="{{i.uploadImg.url}}" style="position:absolute;
            top:0;right:0;
            height:200px !imprtant;width:300px;max-height:200px; "> <br>
        </div>
        <div class="col">


                    <h2>{{i.pname}}</h2><br>
                    <hr>
                    <p>
                      {{i.mobile}}
                    </p>

                    <p>
                      {{i.address}}
                    </p>

                    <p>
                      {{i.email}}
                    </p>

                    <p>
                      {{i.desc}}
                    </p>
                    {% load static %}
                    <ul style="margin:0;padding:0; list-style:none;">
                        <li style="display:inline-block; magin-right:5px;">
                            <a href="{{i.facebook}}">
                            <img src="{% static "/assets/fb.png" %}" style="max-width:30px;">
                            </a>
                        </li>
                                              <li style="display:inline-block; magin-right:5px;">
                                                  <a href="{{i.twitter}}">
                            <img src="{% static "/assets/tw.png" %}" style="max-width:30px;">
                            </a>
                        </li>
                                              <li style="display:inline-block; magin-right:5px;">
                                                  <a href="{{i.instagram}}">
                            <img src="{% static "/assets/in.png" %}" style="max-width:30px;">
                            </a>
                        </li>
                    </ul>



                {% endfor %}

       <!-- end of the loop -->
      </div>
    </div>
  </div>

</main>
{% include "_footer.html" %}

templates/uploadimg.html
<form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>